# Generated by Django 6.0.6 on 2026-07-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_min_stock',
            field=models.PositiveIntegerField(),
        ),
    ]
