# Generated by Django 6.0.6 on 2026-07-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('deposito', 'Deposito'), ('transferencia', 'Transferencia'), ('yape', 'Yape'), ('efetivo', 'Efectivo')], max_length=20, null=True),
        ),
    ]
