# Generated by Django 6.0.6 on 2026-07-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('deposito', 'Deposito'), ('transferencia', 'Transferencia'), ('yape', 'Yape'), ('efectivo', 'Efectivo')], max_length=20, null=True),
        ),
    ]
